# Form implementation generated from reading ui file 'transform_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(676, 579)
        Dialog.setStyleSheet("background-color: rgb(27, 30, 32);")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(40, 50, 601, 481))
        self.tabWidget.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"font-color: rgb(0,0,255);")
        self.tabWidget.setObjectName("tabWidget")
        self.translate_tab = QtWidgets.QWidget()
        self.translate_tab.setObjectName("translate_tab")
        self.tabWidget.addTab(self.translate_tab, "")
        self.rotate_tab = QtWidgets.QWidget()
        self.rotate_tab.setObjectName("rotate_tab")
        self.groupBox = QtWidgets.QGroupBox(parent=self.rotate_tab)
        self.groupBox.setGeometry(QtCore.QRect(40, 120, 281, 251))
        self.groupBox.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rotate_origin_button = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rotate_origin_button.setGeometry(QtCore.QRect(20, 40, 221, 20))
        self.rotate_origin_button.setStyleSheet("")
        self.rotate_origin_button.setObjectName("rotate_origin_button")
        self.rotete_point_button = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rotete_point_button.setGeometry(QtCore.QRect(20, 80, 221, 20))
        self.rotete_point_button.setObjectName("rotete_point_button")
        self.rotate_center_button = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rotate_center_button.setGeometry(QtCore.QRect(20, 120, 241, 20))
        self.rotate_center_button.setObjectName("rotate_center_button")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 131, 16))
        self.label_2.setObjectName("label_2")
        self.angulo_input = QtWidgets.QLineEdit(parent=self.groupBox)
        self.angulo_input.setGeometry(QtCore.QRect(20, 210, 113, 22))
        self.angulo_input.setObjectName("angulo_input")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.rotate_tab)
        self.buttonBox.setGeometry(QtCore.QRect(240, 410, 341, 32))
        self.buttonBox.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(parent=self.rotate_tab)
        self.label_3.setGeometry(QtCore.QRect(370, 30, 211, 341))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.rotate_tab, "")
        self.scaling_tab = QtWidgets.QWidget()
        self.scaling_tab.setObjectName("scaling_tab")
        self.tabWidget.addTab(self.scaling_tab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.translate_tab.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.translate_tab), _translate("Dialog", "Translate"))
        self.rotate_origin_button.setText(_translate("Dialog", "Rotate about the origin"))
        self.rotete_point_button.setText(_translate("Dialog", "Rotate about a point"))
        self.rotate_center_button.setText(_translate("Dialog", "Rotate about the center of an object"))
        self.label_2.setText(_translate("Dialog", "Rotation angle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rotate_tab), _translate("Dialog", "Rotate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scaling_tab), _translate("Dialog", "Scaling"))
