# Form implementation generated from reading ui file '/home/victoria/pastinha/cg/src/view/bezier_view/gui_bezier.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 419)
        Dialog.setStyleSheet("background-color: rgb(86, 43, 0);")
        self.create_bezier_button = QtWidgets.QPushButton(parent=Dialog)
        self.create_bezier_button.setGeometry(QtCore.QRect(150, 370, 101, 31))
        self.create_bezier_button.setObjectName("create_bezier_button")
        self.points_lbl = QtWidgets.QLabel(parent=Dialog)
        self.points_lbl.setGeometry(QtCore.QRect(40, 120, 281, 21))
        self.points_lbl.setObjectName("points_lbl")
        self.points_lbl_2 = QtWidgets.QLabel(parent=Dialog)
        self.points_lbl_2.setGeometry(QtCore.QRect(40, 20, 281, 21))
        self.points_lbl_2.setObjectName("points_lbl_2")
        self.name_curve_bezier = QtWidgets.QLineEdit(parent=Dialog)
        self.name_curve_bezier.setGeometry(QtCore.QRect(40, 50, 161, 31))
        self.name_curve_bezier.setObjectName("name_curve_bezier")
        self.input_bezier = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.input_bezier.setGeometry(QtCore.QRect(40, 150, 291, 211))
        self.input_bezier.setObjectName("input_bezier")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.create_bezier_button.setText(_translate("Dialog", "Create bezier"))
        self.points_lbl.setText(_translate("Dialog", "points:   (x1,y1),(x2,y2) ... (xn,yn)"))
        self.points_lbl_2.setText(_translate("Dialog", "points:   (x1,y1),(x2,y2) ... (xn,yn)"))
