# Form implementation generated from reading ui file '/home/victoria/pastinha/cg/src/view/bezier_view/gui_bezier.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(416, 468)
        Dialog.setStyleSheet("background-color: rgb(86, 43, 0);")
        self.points_lbl = QtWidgets.QLabel(parent=Dialog)
        self.points_lbl.setGeometry(QtCore.QRect(40, 120, 281, 21))
        self.points_lbl.setObjectName("points_lbl")
        self.points_lbl_2 = QtWidgets.QLabel(parent=Dialog)
        self.points_lbl_2.setGeometry(QtCore.QRect(40, 20, 281, 21))
        self.points_lbl_2.setObjectName("points_lbl_2")
        self.name_curve_bezier = QtWidgets.QLineEdit(parent=Dialog)
        self.name_curve_bezier.setGeometry(QtCore.QRect(40, 50, 161, 31))
        self.name_curve_bezier.setObjectName("name_curve_bezier")
        self.input_bezier = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.input_bezier.setGeometry(QtCore.QRect(40, 150, 291, 211))
        self.input_bezier.setObjectName("input_bezier")
        self.create_bezier_button = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.create_bezier_button.setGeometry(QtCore.QRect(120, 410, 171, 51))
        self.create_bezier_button.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.create_bezier_button.setObjectName("create_bezier_button")
        self.set_color_bezier = QtWidgets.QPushButton(parent=Dialog)
        self.set_color_bezier.setGeometry(QtCore.QRect(40, 380, 80, 22))
        self.set_color_bezier.setObjectName("set_color_bezier")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.points_lbl.setText(_translate("Dialog", "points:   (x1,y1),(x2,y2) ... (xn,yn)"))
        self.points_lbl_2.setText(_translate("Dialog", "name:"))
        self.set_color_bezier.setText(_translate("Dialog", "Set color"))
