# Form implementation generated from reading ui file '/home/victoria/pastinha/cg/src/view/create_object_view/gui_create_object.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(568, 275)
        Dialog.setStyleSheet("background-color: rgb(86, 43, 0);")
        self.name_ln = QtWidgets.QLineEdit(parent=Dialog)
        self.name_ln.setGeometry(QtCore.QRect(40, 60, 161, 31))
        self.name_ln.setObjectName("name_ln")
        self.points_lbl = QtWidgets.QLabel(parent=Dialog)
        self.points_lbl.setGeometry(QtCore.QRect(40, 100, 251, 21))
        self.points_lbl.setObjectName("points_lbl")
        self.name_lbl = QtWidgets.QLabel(parent=Dialog)
        self.name_lbl.setGeometry(QtCore.QRect(50, 30, 58, 16))
        self.name_lbl.setObjectName("name_lbl")
        self.points_ln = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.points_ln.setGeometry(QtCore.QRect(40, 130, 281, 101))
        self.points_ln.setObjectName("points_ln")
        self.confirm_create_object = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.confirm_create_object.setGeometry(QtCore.QRect(380, 230, 167, 24))
        self.confirm_create_object.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.NoButton)
        self.confirm_create_object.setObjectName("confirm_create_object")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(370, 160, 171, 91))
        self.frame.setStyleSheet("background-color: rgb(62, 31, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.color_button = QtWidgets.QPushButton(parent=self.frame)
        self.color_button.setGeometry(QtCore.QRect(30, 50, 81, 31))
        self.color_button.setStyleSheet("")
        self.color_button.setObjectName("color_button")
        self.radioButton = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 129, 20))
        self.radioButton.setObjectName("radioButton")
        self.obj_type_comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.obj_type_comboBox.setGeometry(QtCore.QRect(372, 60, 161, 32))
        self.obj_type_comboBox.setObjectName("obj_type_comboBox")
        self.name_lbl_2 = QtWidgets.QLabel(parent=Dialog)
        self.name_lbl_2.setGeometry(QtCore.QRect(370, 30, 111, 16))
        self.name_lbl_2.setObjectName("name_lbl_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.points_lbl.setText(_translate("Dialog", "points:   (x1,y1),(x2,y2) ... (xn,yn)"))
        self.name_lbl.setText(_translate("Dialog", "name:"))
        self.color_button.setText(_translate("Dialog", "set color"))
        self.radioButton.setText(_translate("Dialog", "rachurado"))
        self.name_lbl_2.setText(_translate("Dialog", "object type:"))
